package br.com.gerenciadornet.entity;

// Generated 14/07/2010 16:57:06 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcessoId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class AcessoId implements java.io.Serializable {

	private int codUsuario;
	private int codTransacao;

	public AcessoId() {
	}

	public AcessoId(int codUsuario, int codTransacao) {
		this.codUsuario = codUsuario;
		this.codTransacao = codTransacao;
	}

	@Column(name = "cod_usuario", nullable = false)
	public int getCodUsuario() {
		return this.codUsuario;
	}

	public void setCodUsuario(int codUsuario) {
		this.codUsuario = codUsuario;
	}

	@Column(name = "cod_transacao", nullable = false)
	public int getCodTransacao() {
		return this.codTransacao;
	}

	public void setCodTransacao(int codTransacao) {
		this.codTransacao = codTransacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcessoId))
			return false;
		AcessoId castOther = (AcessoId) other;

		return (this.getCodUsuario() == castOther.getCodUsuario())
				&& (this.getCodTransacao() == castOther.getCodTransacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodUsuario();
		result = 37 * result + this.getCodTransacao();
		return result;
	}

}
