package br.com.gerenciadornet.entity;

// Generated 16/07/2010 17:48:32 by Hibernate Tools 3.2.5.Beta

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.NotNull;

/**
 * AcessoDefault generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "acesso_default")
public class AcessoDefault implements java.io.Serializable {

	private AcessoDefaultId id;
	
	private Transacao transacao = new Transacao();
	
	private Perfil perfil = new Perfil();

	public AcessoDefault(Transacao transacao, Perfil perfil) {
		this.transacao = transacao;
		this.perfil = perfil;
	}

	public AcessoDefault() {
	}

	public AcessoDefault(AcessoDefaultId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codPerfil", column = @Column(name = "cod_perfil", nullable = false)),
			@AttributeOverride(name = "codTransacao", column = @Column(name = "cod_transacao", nullable = false)) })
	@NotNull
	public AcessoDefaultId getId() {
		return this.id;
	}

	public void setId(AcessoDefaultId id) {
		this.id = id;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_transacao", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Transacao getTransacao() {
		return transacao;
	}

	public void setTransacao(Transacao transacao) {
		this.transacao = transacao;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_perfil", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Perfil getPerfil() {
		return perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

}
