package br.com.gerenciadornet.entity;

// Generated 16/07/2010 17:48:32 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcessoDefaultId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class AcessoDefaultId implements java.io.Serializable {

	private int codPerfil;
	private int codTransacao;

	public AcessoDefaultId() {
	}

	public AcessoDefaultId(int codPerfil, int codTransacao) {
		this.codPerfil = codPerfil;
		this.codTransacao = codTransacao;
	}

	@Column(name = "cod_perfil", nullable = false)
	public int getCodPerfil() {
		return this.codPerfil;
	}

	public void setCodPerfil(int codPerfil) {
		this.codPerfil = codPerfil;
	}

	@Column(name = "cod_transacao", nullable = false)
	public int getCodTransacao() {
		return this.codTransacao;
	}

	public void setCodTransacao(int codTransacao) {
		this.codTransacao = codTransacao;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcessoDefaultId))
			return false;
		AcessoDefaultId castOther = (AcessoDefaultId) other;

		return (this.getCodPerfil() == castOther.getCodPerfil())
				&& (this.getCodTransacao() == castOther.getCodTransacao());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodPerfil();
		result = 37 * result + this.getCodTransacao();
		return result;
	}

}
