package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Categoria generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "categoria")
public class Categoria implements java.io.Serializable {

	private Integer codCategoria;
	private String nomeCategoria;
	private boolean inExclusao;
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Categoria() {
	}

	public Categoria(String nomeCategoria, boolean inExclusao) {
		this.nomeCategoria = nomeCategoria;
		this.inExclusao = inExclusao;
	}

	public Categoria(String nomeCategoria, boolean inExclusao,
			Set<Produto> produtos) {
		this.nomeCategoria = nomeCategoria;
		this.inExclusao = inExclusao;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cod_categoria", unique = true, nullable = false)
	public Integer getCodCategoria() {
		return this.codCategoria;
	}

	public void setCodCategoria(Integer codCategoria) {
		this.codCategoria = codCategoria;
	}

	@Column(name = "nome_categoria", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getNomeCategoria() {
		return this.nomeCategoria;
	}

	public void setNomeCategoria(String nomeCategoria) {
		this.nomeCategoria = nomeCategoria;
	}

	@Column(name = "in_exclusao", nullable = false)
	public boolean getInExclusao() {
		return this.inExclusao;
	}

	public void setInExclusao(boolean inExclusao) {
		this.inExclusao = inExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categoria")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

}
