package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Endereco generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "endereco")
public class Endereco implements java.io.Serializable {

	private int codEndereco;
	private Cliente cliente;
	private Fornecedor fornecedor;
	private Usuario usuario;
	private String endereco;
	private String numero;
	private String complemento;
	private String bairro;
	private String cidade;
	private String uf;
	private String telefone1;
	private String tefefone2;
	private String cep;

	public Endereco() {
	}

	public Endereco(Usuario usuario, String endereco) {
		this.usuario = usuario;
		this.endereco = endereco;
	}

	public Endereco( Cliente cliente, Fornecedor fornecedor,
			Usuario usuario, String endereco, String numero,
			String complemento, String bairro, String cidade, String uf,
			String telefone1, String tefefone2) {
		this.cliente = cliente;
		this.fornecedor = fornecedor;
		this.usuario = usuario;
		this.endereco = endereco;
		this.numero = numero;
		this.complemento = complemento;
		this.bairro = bairro;
		this.cidade = cidade;
		this.uf = uf;
		this.telefone1 = telefone1;
		this.tefefone2 = tefefone2;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cod_endereco", unique = true, nullable = false)
	public int getCodEndereco() {
		return this.codEndereco;
	}

	public void setCodEndereco(int codEndereco) {
		this.codEndereco = codEndereco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_cliente")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_fornecedor")
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "endereco", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "numero", length = 15)
	@Length(max = 15)
	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	@Column(name = "complemento", length = 100)
	@Length(max = 100)
	public String getComplemento() {
		return this.complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	@Column(name = "bairro", length = 50)
	@Length(max = 50)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "cidade", length = 50)
	@Length(max = 50)
	public String getCidade() {
		return this.cidade;
	}

	public void setCidade(String cidade) {
		this.cidade = cidade;
	}

	@Column(name = "uf", length = 2)
	@Length(max = 2)
	public String getUf() {
		return this.uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	@Column(name = "telefone1", length = 20)
	@Length(max = 20)
	public String getTelefone1() {
		return this.telefone1;
	}

	public void setTelefone1(String telefone1) {
		this.telefone1 = telefone1;
	}

	@Column(name = "tefefone2", length = 20)
	@Length(max = 20)
	public String getTefefone2() {
		return this.tefefone2;
	}

	public void setTefefone2(String tefefone2) {
		this.tefefone2 = tefefone2;
	}

	@Column(name = "cep", length = 9)
	@Length(max = 9)
	public String getCep()
	{
		return cep;
	}

	public void setCep(String cep)
	{
		this.cep = cep;
	}
}
