package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Historico generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "historico")
public class Historico implements java.io.Serializable {

	private Integer codHistorico;
	private Usuario usuario = new Usuario();
	private String descHistorico;
	private Date dataHistorico;

	public Historico() {
	}

	public Historico(Usuario usuario, String descHistorico, Date dataHistorico) {
		this.usuario = usuario;
		this.descHistorico = descHistorico;
		this.dataHistorico = dataHistorico;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cod_historico", unique = true, nullable = false)
	public Integer getCodHistorico() {
		return this.codHistorico;
	}

	public void setCodHistorico(Integer codHistorico) {
		this.codHistorico = codHistorico;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_usuario", nullable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "desc_historico", nullable = false, length = 200)
	@NotNull
	@Length(max = 200)
	public String getDescHistorico() {
		return this.descHistorico;
	}

	public void setDescHistorico(String descHistorico) {
		this.descHistorico = descHistorico;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_historico", nullable = false, length = 0)
	@NotNull
	public Date getDataHistorico() {
		return this.dataHistorico;
	}

	public void setDataHistorico(Date dataHistorico) {
		this.dataHistorico = dataHistorico;
	}

}
