package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Marca generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "marca")
public class Marca implements java.io.Serializable {

	private Integer codMarca;
	private String nomeMarca;
	private boolean inExclusao;
	private Fornecedor fornecedor = new Fornecedor();
	private Set<Produto> produtos = new HashSet<Produto>(0);

	public Marca() {
	}

	public Marca(String nomeMarca, boolean inExclusao) {
		this.nomeMarca = nomeMarca;
		this.inExclusao = inExclusao;
	}

	public Marca(String nomeMarca, boolean inExclusao, Set<Produto> produtos) {
		this.nomeMarca = nomeMarca;
		this.inExclusao = inExclusao;
		this.produtos = produtos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cod_marca", unique = true, nullable = false)
	public Integer getCodMarca() {
		return this.codMarca;
	}

	public void setCodMarca(Integer codMarca) {
		this.codMarca = codMarca;
	}

	@Column(name = "nome_marca", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getNomeMarca() {
		return this.nomeMarca;
	}

	public void setNomeMarca(String nomeMarca) {
		this.nomeMarca = nomeMarca;
	}

	@Column(name = "in_exclusao", nullable = false)
	public boolean getInExclusao() {
		return this.inExclusao;
	}

	public void setInExclusao(boolean inExclusao) {
		this.inExclusao = inExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "marca")
	public Set<Produto> getProdutos() {
		return this.produtos;
	}

	public void setProdutos(Set<Produto> produtos) {
		this.produtos = produtos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_fornecedor")
	public Fornecedor getFornecedor() {
		return fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

}
