package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutoVendidoId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ProdutoVendidoId implements java.io.Serializable {

	private int codLoteProduto;
	private int codVenda;

	public ProdutoVendidoId() {
	}

	public ProdutoVendidoId(int codLoteProduto, int codVenda) {
		this.codLoteProduto = codLoteProduto;
		this.codVenda = codVenda;
	}

	@Column(name = "cod_lote_produto", nullable = false)
	public int getCodLoteProduto() {
		return this.codLoteProduto;
	}

	public void setCodLoteProduto(int codLoteProduto) {
		this.codLoteProduto = codLoteProduto;
	}

	@Column(name = "cod_venda", nullable = false)
	public int getCodVenda() {
		return this.codVenda;
	}

	public void setCodVenda(int codVenda) {
		this.codVenda = codVenda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoVendidoId))
			return false;
		ProdutoVendidoId castOther = (ProdutoVendidoId) other;

		return (this.getCodLoteProduto() == castOther.getCodLoteProduto())
				&& (this.getCodVenda() == castOther.getCodVenda());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodLoteProduto();
		result = 37 * result + this.getCodVenda();
		return result;
	}

}
