package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.validator.NotNull;

/**
 * ProdutoVendido generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "produto_pedido")
public class ProdutoPedido implements java.io.Serializable {

	private ProdutoPedidoId id;
	private Venda venda;
	private Produto produto = new Produto();
	private int qtd = 1;
	private Float desconto = 0f;
	private Float precoVenda;
	private Boolean inAdicionado = false;
	
	public ProdutoPedido() {
	}
	
	public ProdutoPedido(Produto produto) {
		this.produto = produto;
	}

	public ProdutoPedido(ProdutoPedidoId id, Venda venda,
			Produto produto, int qtd) {
		this.id = id;
		this.venda = venda;
		this.produto = produto;
		this.qtd = qtd;
	}

	public ProdutoPedido(ProdutoPedidoId id, Venda venda,
			Produto produto, int qtd, Float desconto, Float precoVenda) {
		this.id = id;
		this.venda = venda;
		this.produto = produto;
		this.qtd = qtd;
		this.desconto = desconto;
		this.precoVenda = precoVenda;
	}
	
	@EmbeddedId
	@NotNull
	public ProdutoPedidoId getId() {
		return this.id;
	}

	public void setId(ProdutoPedidoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_venda", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Venda getVenda() {
		return this.venda;
	}

	public void setVenda(Venda venda) {
		this.venda = venda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cod_produto", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Produto getProduto() {
		return this.produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	@Column(name = "qtd", nullable = false)
	public int getQtd() {
		return this.qtd;
	}

	public void setQtd(int qtd) {
		this.qtd = qtd;
	}

	@Column(name = "desconto", precision = 12, scale = 0)
	public Float getDesconto() {
		return this.desconto;
	}

	public void setDesconto(Float desconto) {
		this.desconto = desconto;
	}

	@Column(name = "preco_venda", precision = 12, scale = 0)
	public Float getPrecoVenda() {
		return this.precoVenda;
	}

	public void setPrecoVenda(Float precoVenda) {
		this.precoVenda = precoVenda;
	}
	
	@Transient
	public Boolean getInAdicionado() {
	    return inAdicionado;
	}

	public void setInAdicionado(Boolean novoInAdicionado) {
	    inAdicionado = novoInAdicionado;
	}
}
