package br.com.gerenciadornet.entity;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdutoVendidoId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class ProdutoPedidoId implements java.io.Serializable {

	private int codProduto;
	private int codVenda;

	public ProdutoPedidoId() {
	}

	public ProdutoPedidoId(int codProduto, int codVenda) {
		this.codProduto = codProduto;
		this.codVenda = codVenda;
	}

	@Column(name = "cod_produto", nullable = false, updatable=false)
	public int getcodProduto() {
		return this.codProduto;
	}

	public void setcodProduto(int codProduto) {
		this.codProduto = codProduto;
	}

	@Column(name = "cod_venda", nullable = false, updatable=false)
	public int getCodVenda() {
		return this.codVenda;
	}

	public void setCodVenda(int codVenda) {
		this.codVenda = codVenda;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoPedidoId))
			return false;
		ProdutoPedidoId castOther = (ProdutoPedidoId) other;

		return (this.getcodProduto() == castOther.getcodProduto())
				&& (this.getCodVenda() == castOther.getCodVenda());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getcodProduto();
		result = 37 * result + this.getCodVenda();
		return result;
	}

}
