package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Servico generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "servico")
public class Servico implements java.io.Serializable {

	private Integer codServico;
	private String descServico;
	private Float precoCusto;
	private Float precoServico;
	private boolean inExclusao;
	private Set<ServicoRealizado> servicoRealizados = new HashSet<ServicoRealizado>(0);

	public Servico() {
	}

	public Servico(String descServico, boolean inExclusao) {
		this.descServico = descServico;
		this.inExclusao = inExclusao;
	}

	public Servico(String descServico, Float precoServico, boolean inExclusao,
			Set<ServicoRealizado> servicoRealizados) {
		this.descServico = descServico;
		this.precoServico = precoServico;
		this.inExclusao = inExclusao;
		this.servicoRealizados = servicoRealizados;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cod_servico", unique = true, nullable = false)
	public Integer getCodServico() {
		return this.codServico;
	}

	public void setCodServico(Integer codServico) {
		this.codServico = codServico;
	}

	@Column(name = "desc_servico", nullable = false, length = 60)
	@NotNull
	@Length(max = 60)
	public String getDescServico() {
		return this.descServico;
	}

	public void setDescServico(String descServico) {
		this.descServico = descServico;
	}

	@Column(name = "preco_servico", precision = 12, scale = 2)
	public Float getPrecoServico() {
		return this.precoServico;
	}

	public void setPrecoServico(Float precoServico) {
		this.precoServico = precoServico;
	}

	@Column(name = "in_exclusao", nullable = false)
	public boolean isInExclusao() {
		return this.inExclusao;
	}

	public void setInExclusao(boolean inExclusao) {
		this.inExclusao = inExclusao;
	}

	@OneToMany(cascade= CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "servico")	
	public Set<ServicoRealizado> getServicoRealizados() {
		return this.servicoRealizados;
	}

	public void setServicoRealizados(Set<ServicoRealizado> servicoRealizados) {
		this.servicoRealizados = servicoRealizados;
	}

	@Column(name = "preco_custo", precision = 12, scale = 2)
	public Float getPrecoCusto() {
		return precoCusto;
	}

	public void setPrecoCusto(Float precoCusto) {
		this.precoCusto = precoCusto;
	}

	
}
