package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;
 
/**
 * TipoPagamento generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "tipo_pagamento")
public class TipoPagamento implements java.io.Serializable {

	private int 		codTipoPagamento;
	private String 		descTipoPagamento;
	private boolean 	inExclusao;
	private Integer 	numVezes;
	private Integer 	intervaloDias;
	private Integer 	diasCarencia;
	private boolean 	inECommerce;
	private boolean 	inGN;
	private boolean 	inGNb2b;
	private Set<Venda> 	vendas = new HashSet<Venda>(0);
	private Set<Compra> compras = new HashSet<Compra>(0);

	public TipoPagamento() {
	}

	public TipoPagamento(int codTipoPagamento, String descTipoPagamento,
			boolean inExclusao) {
		this.codTipoPagamento = codTipoPagamento;
		this.descTipoPagamento = descTipoPagamento;
		this.inExclusao = inExclusao;
	}

	public TipoPagamento(int codTipoPagamento, String descTipoPagamento,
			boolean inExclusao, Set<Venda> vendas, Set<Compra> compras) {
		this.codTipoPagamento = codTipoPagamento;
		this.descTipoPagamento = descTipoPagamento;
		this.inExclusao = inExclusao;
		this.vendas = vendas;
		this.compras = compras;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)  
	@Column(name = "cod_tipo_pagamento", unique = true, nullable = false)
	public int getCodTipoPagamento() {
		return this.codTipoPagamento;
	}

	public void setCodTipoPagamento(int codTipoPagamento) {
		this.codTipoPagamento = codTipoPagamento;
	}

	@Column(name = "desc_tipo_pagamento", nullable = false, length = 30)
	@NotNull
	@Length(max = 30)
	public String getDescTipoPagamento() {
		return this.descTipoPagamento;
	}

	public void setDescTipoPagamento(String descTipoPagamento) {
		this.descTipoPagamento = descTipoPagamento;
	}

	@Column(name = "in_exclusao", nullable = false)
	public boolean isInExclusao() {
		return this.inExclusao;
	}

	public void setInExclusao(boolean inExclusao) {
		this.inExclusao = inExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPagamento")
	public Set<Venda> getVendas() {
		return this.vendas;
	}

	public void setVendas(Set<Venda> vendas) {
		this.vendas = vendas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPagamento")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

	@Column(name = "num_vezes", nullable = false)
	public Integer getNumVezes(){
		return numVezes;
	}

	public void setNumVezes(Integer numVezes){
		this.numVezes = numVezes;
	}

	@Column(name = "intervalo_dias", nullable = false)
	public Integer getIntervaloDias(){
		return intervaloDias;
	}

	public void setIntervaloDias(Integer intervaloDias){
		this.intervaloDias = intervaloDias;
	}

	@Column(name = "dias_carencia", nullable = false)
	public Integer getDiasCarencia()
	{
		return diasCarencia;
	}

	public void setDiasCarencia(Integer diasCarencia)
	{
		this.diasCarencia = diasCarencia;
	}

	@Column(name = "in_ecommerce", nullable = false)
	public boolean isInECommerce() {
		return inECommerce;
	}

	public void setInECommerce(boolean inECommerce) {
		this.inECommerce = inECommerce;
	}

	@Column(name = "in_gn", nullable = false)
	public boolean isInGN() {
		return inGN;
	}

	public void setInGN(boolean inGN) {
		this.inGN = inGN;
	}

	@Column(name = "in_gnb2b", nullable = false)
	public boolean isInGNb2b() {
		return inGNb2b;
	}

	public void setInGNb2b(boolean inGNb2b) {
		this.inGNb2b = inGNb2b;
	}
}
