package br.com.gerenciadornet.entity;

// Generated 14/07/2010 16:57:06 by Hibernate Tools 3.2.5.Beta

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Transacao generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "transacao")
public class Transacao implements java.io.Serializable {

	private Integer codTransacao;
	private String siglaTransacao;
	private String nome;
	private String descTransacao;
	private boolean inExclusao;

	public Transacao() {
	}

	public Transacao(String siglaTransacao, String descTransacao,
			boolean inExclusao) {
		this.siglaTransacao = siglaTransacao;
		this.descTransacao = descTransacao;
		this.inExclusao = inExclusao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cod_transacao", unique = true, nullable = false)
	public Integer getCodTransacao() {
		return this.codTransacao;
	}

	public void setCodTransacao(Integer codTransacao) {
		this.codTransacao = codTransacao;
	}

	@Column(name = "sigla_transacao", nullable = false, length = 6)
	@NotNull
	@Length(max = 5)
	public String getSiglaTransacao() {
		return this.siglaTransacao;
	}

	public void setSiglaTransacao(String siglaTransacao) {
		this.siglaTransacao = siglaTransacao;
	}

	@Column(name = "desc_transacao", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getDescTransacao() {
		return this.descTransacao;
	}

	public void setDescTransacao(String descTransacao) {
		this.descTransacao = descTransacao;
	}

	@Column(name = "in_exclusao", nullable = false)
	public boolean isInExclusao() {
		return this.inExclusao;
	}

	public void setInExclusao(boolean inExclusao) {
		this.inExclusao = inExclusao;
	}

	@Column(name = "nome", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
