package br.com.gerenciadornet.entity;

// Generated 09/02/2010 16:40:06 by Hibernate Tools 3.2.5.Beta

import java.util.HashSet;
import java.util.Set;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.validator.Length;
import org.hibernate.validator.NotNull;

/**
 * Vendedor generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "vendedor")
public class Vendedor implements java.io.Serializable {

	private VendedorId id;
	private Fornecedor fornecedor = new Fornecedor();
	private String nomeVendedor;
	private String emailVendedor;
	private String telefoneVendedor;
	private Boolean inExclusao;
	private Set<Compra> compras = new HashSet<Compra>(0);

	public Vendedor() {
	}

	public Vendedor(Fornecedor fornecedor, String nomeVendedor) {
		this.fornecedor = fornecedor;
		this.nomeVendedor = nomeVendedor;
	}

	public Vendedor(Fornecedor fornecedor, String nomeVendedor,
			String emailVendedor, String telefoneVendedor, Boolean inExclusao,
			Set<Compra> compras) {
		this.fornecedor = fornecedor;
		this.nomeVendedor = nomeVendedor;
		this.emailVendedor = emailVendedor;
		this.telefoneVendedor = telefoneVendedor;
		this.inExclusao = inExclusao;
		this.compras = compras;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "codVendedor", column = @Column(name = "cod_vendedor", nullable = false)),
			@AttributeOverride(name = "codFornecedor", column = @Column(name = "cod_fornecedor", nullable = false)) })
	@NotNull
	public VendedorId getId() {
		return this.id;
	}

	public void setId(VendedorId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cod_fornecedor", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Fornecedor getFornecedor() {
		return this.fornecedor;
	}

	public void setFornecedor(Fornecedor fornecedor) {
		this.fornecedor = fornecedor;
	}

	@Column(name = "nome_vendedor", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	public String getNomeVendedor() {
		return this.nomeVendedor;
	}

	public void setNomeVendedor(String nomeVendedor) {
		this.nomeVendedor = nomeVendedor;
	}

	@Column(name = "email_vendedor", length = 100)
	@Length(max = 100)
	public String getEmailVendedor() {
		return this.emailVendedor;
	}

	public void setEmailVendedor(String emailVendedor) {
		this.emailVendedor = emailVendedor;
	}

	@Column(name = "telefone_vendedor", length = 20)
	@Length(max = 20)
	public String getTelefoneVendedor() {
		return this.telefoneVendedor;
	}

	public void setTelefoneVendedor(String telefoneVendedor) {
		this.telefoneVendedor = telefoneVendedor;
	}

	@Column(name = "in_exclusao", nullable = false)
	public Boolean getInExclusao() {
		return this.inExclusao;
	}

	public void setInExclusao(Boolean inExclusao) {
		this.inExclusao = inExclusao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vendedor")
	public Set<Compra> getCompras() {
		return this.compras;
	}

	public void setCompras(Set<Compra> compras) {
		this.compras = compras;
	}

}
